CREATE TABLE audit_events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic        VARCHAR(50)  NOT NULL,
    event_type   VARCHAR(100) NOT NULL,
    user_id      BIGINT,
    game_id      BIGINT,
    payload_json TEXT         NOT NULL,
    occurred_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_audit_topic_type ON audit_events (topic, event_type);
CREATE INDEX idx_audit_occurred   ON audit_events (occurred_at DESC);
CREATE INDEX idx_audit_user       ON audit_events (user_id);
CREATE INDEX idx_audit_game       ON audit_events (game_id);