CREATE TABLE library_entries (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL,
    game_id      BIGINT NOT NULL,
    is_favorite  BOOLEAN NOT NULL DEFAULT FALSE,
    hours_played DOUBLE PRECISION NOT NULL DEFAULT 0,
    added_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_library_user_game UNIQUE (user_id, game_id),
    CONSTRAINT fk_library_game FOREIGN KEY (game_id) REFERENCES games (id) ON DELETE CASCADE
);