CREATE TABLE library_categories (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    name       VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_library_category_user_name UNIQUE (user_id, name)
);

CREATE TABLE library_entry_categories (
    library_entry_id BIGINT NOT NULL,
    category_id      BIGINT NOT NULL,
    PRIMARY KEY (library_entry_id, category_id),
    CONSTRAINT fk_lec_entry FOREIGN KEY (library_entry_id)
        REFERENCES library_entries (id) ON DELETE CASCADE,
    CONSTRAINT fk_lec_category FOREIGN KEY (category_id)
        REFERENCES library_categories (id) ON DELETE CASCADE
);