CREATE TABLE wishlist_entries (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  BIGINT NOT NULL,
    game_id  BIGINT NOT NULL,
    added_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_wishlist_user_game UNIQUE (user_id, game_id),
    CONSTRAINT fk_wishlist_game FOREIGN KEY (game_id)
        REFERENCES games (id) ON DELETE CASCADE
);